server:
  port: 9002
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/postbar_db?useSSL=false&characterEncoding=utf8
      username: root
      password: kang
      driver-class-name: com.mysql.jdbc.Driver
      #上传文件大小的设置
  servlet:
    multipart:
      max-file-size: 512MB #一个文件最大的大小
      max-request-size: 1028MB #一次请求的最大大小
  #      eureka
  application:
    name: post-server


eureka:
  instance:
    hostname: localhost
    status-page-url: http://localhost:10001/actuator
  client:
    registerWithEureka: true # 是否将自己注册到 Eureka 注册中心
    fetchRegistry: true # 是否获取Eureka注册中心中的所有服务
    serviceUrl:
      # 设置Eureka Server的服务URL
      defaultZone: http://localhost:10001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

